# Generated by Django 6.0.2 on 2026-04-29 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('id_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на фото')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес (adress)')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (data)')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Является работником (is_employeee)')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_cm.city', verbose_name='Город (id_city)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_cm.product', verbose_name='Продукт (id_product)')),
            ],
            options={
                'verbose_name': 'Доступность продукта в городе',
                'db_table': 'CityList',
            },
        ),
        migrations.CreateModel(
            name='Refferals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_link', models.URLField(verbose_name='Ссылка на рефералку')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='server_cm.product', verbose_name='Продукт (product_id)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='server_cm.user', verbose_name='Клиент (client_id)')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'db_table': 'Refferals',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотрено')),
                ('clicks_count', models.IntegerField(default=0, verbose_name='Переходов')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='server_cm.refferals', verbose_name='Реферал (id_ref)')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'db_table': 'Statistics',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_cm.product', verbose_name='Продукт (product_id)')),
                ('ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_cm.refferals', verbose_name='Реферал (ref_id)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_cm.user', verbose_name='Клиент (client_id)')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='server_cm.user', verbose_name='Ответственный (employeey_id)'),
        ),
    ]
