# Generated by Django 6.0.2 on 2026-04-26 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес проживания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('number_message', models.IntegerField(verbose_name='Номер сообщения')),
                ('technical_specialist', models.ForeignKey(db_column='technical_specialist_id', on_delete=django.db.models.deletion.CASCADE, to='server_cm.employee', verbose_name='Специалист поддержки')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Чат',
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('id_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на изображение')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('date', models.DateField(db_column='data', verbose_name='Дата создания/актуальности')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория')),
                ('city', models.ForeignKey(blank=True, db_column='address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_cm.city', verbose_name='Город (address)')),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_cm.employee', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Банковский продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_url', models.URLField(blank=True, db_column='referral_url', null=True, verbose_name='Ссылка на рефералку')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='server_cm.employee', verbose_name='Сотрудник')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='server_cm.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Реферальная ссылка',
                'verbose_name_plural': 'Рефералки',
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='server_cm.product', verbose_name='Продукт')),
                ('referral', models.ForeignKey(blank=True, db_column='ref_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_cm.referral', verbose_name='Реферальная ссылка')),
                ('client', models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_cm.user', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(db_column='view_count', default=0, verbose_name='Количество просмотров')),
                ('clicks_count', models.IntegerField(db_column='click_count', default=0, verbose_name='Количество переходов')),
                ('request', models.ForeignKey(db_column='id_ref', on_delete=django.db.models.deletion.CASCADE, to='server_cm.request', verbose_name='Заявка/Рефералка')),
            ],
            options={
                'verbose_name': 'Запись статистики',
                'verbose_name_plural': 'Дашборд',
                'db_table': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='TechSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server_cm.employee', verbose_name='Сотрудник поддержки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_cm.user', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Тикет поддержки',
                'verbose_name_plural': 'Техподдержка',
                'db_table': 'tech_support',
            },
        ),
        migrations.CreateModel(
            name='ProductCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.CASCADE, to='server_cm.city', verbose_name='Город')),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.CASCADE, to='server_cm.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Доступность в городе',
                'verbose_name_plural': 'Доступность продуктов',
                'db_table': 'product_cities',
                'unique_together': {('product', 'city')},
            },
        ),
    ]
