# Generated by Django 6.0.2 on 2026-04-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_cm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='last_name',
        ),
    ]
