# Generated by Django 6.0.2 on 2026-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_cm', '0002_rename_surname_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
