# Generated by Django 6.0.2 on 2026-04-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_cm', '0003_user_id_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='employee',
        ),
    ]
