# Generated by Django 6.0.2 on 2026-05-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_cm', '0004_remove_product_address_remove_product_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль (хешированный)')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('code', models.CharField(max_length=10, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ожидающий регистрации пользователь',
                'verbose_name_plural': 'Ожидающие регистрации',
                'db_table': 'RegisterUser',
            },
        ),
    ]
